services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: claimflow-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: claimflow
      POSTGRES_USER: claimflow_admin
      POSTGRES_PASSWORD: claimflow_dev_2026
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claimflow_admin -d claimflow"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: claimflow-pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./userlist.txt:/etc/pgbouncer/userlist.txt:ro
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: claimflow-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: claimflow
      RABBITMQ_DEFAULT_PASS: claimflow_dev_2026
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/ClaimFlow.Api/Dockerfile
    container_name: claimflow-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=claimflow;Username=claimflow_admin;Password=claimflow_dev_2026"
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: claimflow
      RabbitMq__Password: claimflow_dev_2026
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ui:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: claimflow-ui
    ports:
      - "3000:80" 
    environment:
      - VITE_API_URL=http://localhost:5000/api 
    depends_on:
      - api


volumes:
  pgdata:
